#server:
#  port: 8702
#spring:
#  application:
#    name: data-fund-collect
#  cloud:
#    stream:
#      defaultBinder: company-overview
#      bindings:
#        produce-company-overview:
#          binder: company-overview
#          destination: topic-company-overview
#          contentType: application/*+avro
#          useNativeEncoding: true
#        produce-company-list:
#          binder: company-list
#          destination: topic-company-list
#          contentType: application/*+avro
#          useNativeEncoding: true
#        produce-fund-list:
#          binder: fund-list
#          destination: topic-fund-list
#          contentType: application/*+avro
#          useNativeEncoding: true
#        produce-fund-archives:
#          binder: fund-archives
#          destination: topic-fund-archives
#          contentType: application/*+avro
#          useNativeEncoding: true
#      binders:
#        company-overview:
#          type: kafka
#          environment:
#            spring:
#              cloud:
#                stream:
#                  kafka:
#                    binder:
#                      brokers: 192.168.33.40:9092
#                      auto-create-topics: true
#        company-list:
#          type: kafka
#          environment:
#            spring:
#              cloud:
#                stream:
#                  kafka:
#                    binder:
#                      brokers: 192.168.33.40:9092
#                      auto-create-topics: true
#        fund-list:
#          type: kafka
#          environment:
#            spring:
#              cloud:
#                stream:
#                  kafka:
#                    binder:
#                      brokers: 192.168.33.40:9092
#                      auto-create-topics: true
#        fund-archives:
#          type: kafka
#          environment:
#            spring:
#              cloud:
#                stream:
#                  kafka:
#                    binder:
#                      brokers: 192.168.33.40:9092
#                      auto-create-topics: true
#    nacos:
#      config:
#        server-addr: localhost:8848
#        file-extension: yaml
#      discovery:
#        server-addr: localhost:8848
#management:
#  endpoints:
#    web:
#      exposure:
#        include: '*'
#logging:
#  level:
#    com.baomidou: debug