##server:
##  port: 8701
##spring:
##  application:
##    name: data-fund-collect
##  cloud:
##    nacos:
##      config:
##        server-addr: localhost:8848
##        file-extension: yaml
##  profiles:
##    active: dev
##rocketmq:
##  name-server: http://127.0.0.1:9876 #rocketmq服务地址
##  producer:
##    group: fund-collect #自定义的组名称
##    send-message-timeout: 3000  #消息发送超时时长
##spring:
##  cloud:
##    stream:
##      kafka:
##        binder:
##          brokers: localhost:9092         #Kafka的消息中间件服务器
##          auto-create-topics: true        #如果设置为false,就不会自动创建Topic 有可能你Topic还没创建就直接调用了。
##      bindings:
##        fundChannel:
##          destination: data-collect
#spring:
#  cloud:
#    stream:
#      bindings:
#        producer-customer-topic-avro:
#          binder: kafka_avro_producer
#          destination: customer-topic-avro
#          contentType: application/*+avro
#          useNativeEncoding: true
#      binders:
#        kafka_avro_producer:
#          type: kafka
#          environment:
#            spring:
#              cloud:
#                stream:
#                  kafka:
#                    binder:
##                      producer-properties:
##                        #key.serializer: org.apache.kafka.common.serialization.StringSerializer
##                        value.serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
##                        schema.registry.url: http://localhost:8085
#                      brokers: http://localhost:9092